### ISSUE TITLE
UiKit.Buttons

### ISSUE THREAD

**Issue by avanisimov** [INtouch-YP/intouch-android#11]
https://www.figma.com/file/y1VbKd1PHJ3gwP5bKAqUOb/INtouch-(%D1%80%D0%B5%D0%B3%D0%B8%D1%81%D1%82%D1%80%D0%B0%D1%86%D0%B8%D1%8F-%2B-My-plan)?type=design&node-id=5131-28212&mode=design&t=TJAuqgT0fG68H2I9-0
![image](https://github.com/INtouch-YP/intouch-android/assets/26187894/e56df127-3ad6-43fe-bac5-274fd939925f)

**Comment by JudjinGM** [comment]
update: new link for https://www.figma.com/file/y1VbKd1PHJ3gwP5bKAqUOb/INtouch-(%D1%80%D0%B5%D0%B3%D0%B8%D1%81%D1%82%D1%80%D0%B0%D1%86%D0%B8%D1%8F-%2B-My-plan)?type=design&node-id=5131-28212&mode=design&t=TJAuqgT0fG68H2I9-0
