### ISSUE TITLE
UiKit.progress bar

### ISSUE THREAD

**Issue by avanisimov** [INtouch-YP/intouch-android#13]
https://www.figma.com/file/SqsUbr00byYiLZHOh9oXmU/InTouch-%D0%9B%D0%9A-%D0%9A%D0%BB%D0%B8%D0%B5%D0%BD%D1%82%D0%B0-(App)-Full-version?type=design&node-id=105-29413&mode=design&t=hIjBQPDTU4JM4rHh-4
![image](https://github.com/INtouch-YP/intouch-android/assets/26187894/462080c7-d8de-4456-9367-98226409f05e)

**Comment by vikseal** [comment]
https://www.figma.com/file/y1VbKd1PHJ3gwP5bKAqUOb/INtouch-(%D1%80%D0%B5%D0%B3%D0%B8%D1%81%D1%82%D1%80%D0%B0%D1%86%D0%B8%D1%8F-%2B-My-plan)?type=design&node-id=5131-27912&mode=design&t=0XZ0lQET3nbRKSC8-4

**Comment by vikseal** [comment]
Пока в работу не берем. В дизайне не используется
