### ISSUE TITLE
При  успешной авторизации переход осуществляется на окно создания пин-кода, а не на главный экран

### ISSUE THREAD

**Issue by yknatalie** [INtouch-YP/intouch-android#149]
**Шаги воспрозведения:**
1 Зарегистрироваться в мобильном приложении как уже прикрепленный к врачу пациент
2 Возникает окно создания пин-кода - создать пин-код
3 Выйти из приложения 
4 Авторизоваться с теми же данными
**Фактический результат:**
Осуществляется переход на экран создания пин-кода
**Ожидаемый результат:**
Осуществляется переход на главный экран
**Номер сборки:**
Сборка 62

**Comment by vikseal** [comment]
Не требует исправления. Так как пин-код хранится локально, и при потере авторизации удаляется. Также соответствует требованиям прописанным в ФЛ
