### ISSUE TITLE
UiKit.Chipss

### ISSUE THREAD

**Issue by avanisimov** [INtouch-YP/intouch-android#15]
https://www.figma.com/file/y1VbKd1PHJ3gwP5bKAqUOb/INtouch-(%D1%80%D0%B5%D0%B3%D0%B8%D1%81%D1%82%D1%80%D0%B0%D1%86%D0%B8%D1%8F-%2B-My-plan)?type=design&node-id=5131-27864&mode=design&t=O8qYMdN9oj9zTC5N-0
![image](https://github.com/INtouch-YP/intouch-android/assets/26187894/3a4ff98c-e0e7-4338-a542-757d047af56a)

**Comment by vikseal** [comment]
Чипсы добавлены. Есть коммент в фигме
