### ISSUE TITLE
Поддержка deeplink  в приложении

### ISSUE THREAD

**Issue by vikseal** [INtouch-YP/intouch-android#46]
Написать json для deeplink.

Статьи по теме:
https://medium.com/androiddevelopers/the-deep-links-crash-course-part-1-introduction-to-deep-links-2189e509e269

https://developer.android.com/studio/write/app-link-indexing

https://developer.android.com/training/app-links/deep-linking

https://developer.android.com/training/app-links/verify-android-applinks

**Comment by JudjinGM** [comment]
Json для домена можно создать используя встроенный инструмент App Link Assistant-Create Applink-Digital Asset Links File Generator
