### ISSUE TITLE
UiKit.Text Fields

### ISSUE THREAD

**Issue by avanisimov** [INtouch-YP/intouch-android#9]
https://www.figma.com/file/SqsUbr00byYiLZHOh9oXmU/InTouch-%D0%9B%D0%9A-%D0%9A%D0%BB%D0%B8%D0%B5%D0%BD%D1%82%D0%B0-(App)-Full-version?type=design&node-id=105-17403&mode=design&t=hIjBQPDTU4JM4rHh-4
![image](https://github.com/INtouch-YP/intouch-android/assets/26187894/478d2fe9-e898-49ef-ad54-41d164f0c071)

**Comment by vikseal** [comment]
![Image](https://github.com/INtouch-YP/intouch-android/assets/1682866/8e1c0873-8dda-4598-9724-b4e5f5c99bec)

Раздел обновлен.  Есть комментарии
